name: Build manuel du jar

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'nom du jar'
        # Default value if no value is explicitly provided
        default: 'popopopo'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Assemble with Gradle
      run: ./gradlew assemble
    - name: 'Get Version Number'
      run: echo "::set-env name=VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
    - name: 'Publish JAR'
      uses: actions/upload-artifact@v2-preview
      with:
        name: ‘MaskModel-${{env.VERSION}}-SNAPSHOT.jar'
        path: build/libs/*-SNAPSHOT.jar
